### ISSUE TITLE
LetterBoxer Ratio set same as iPhone X(19.5:9), run on Sony Xperia 1(21:9) Left, right has issue.

### ISSUE THREAD

**Issue by SyaoranChang** [rabidgremlin/LetterBoxer#1]
HI,

I try LetterBoxer Ratio set same as iPhone X(19.5:9)
Unity resolution set same as Sony Xperia 1 3860x1644(21:9)
Left, right has issue.

Could add LetterBox on left and right?
![Snipaste_2020-09-07_17-44-55](https://user-images.githubusercontent.com/18550228/92374673-a3fac180-f132-11ea-9451-1a3f17d88e8b.png)

![Snipaste_2020-09-07_17-51-12](https://user-images.githubusercontent.com/18550228/92374769-c8569e00-f132-11ea-9864-416a34641208.png)

**Comment by SyaoranChang** [comment]
On Android side
Unity PlayerSettings 
Aspect Ratio Mode set to Custom
Up to 2.166667(iphone X 19.5:9)

And AndroidManifest.xml
Add android:resizeableActivity="false

Then on Sony Xperia 1 3860x1644(21:9)
The Screen will only draw 19.5:9.


Reference:
https://docs.unity3d.com/Manual/class-PlayerSettingsAndroid.html
https://docs.unity3d.com/ScriptReference/PlayerSettings.Android-maxAspectRatio.html
Declare a maximum aspect ratio
https://developer.android.com/guide/practices/screens-distribution

Custom Max Aspect Ratio In Player Settings Isn't Working
https://forum.unity.com/threads/custom-max-aspect-ratio-in-player-settings-isnt-working.900338/
resizeableActivity
https://developer.android.com/reference/android/R.attr#resizeableActivity
https://developer.android.com/reference/android/R.attr#resizeableActivity

**Comment by rabidgremlin** [comment]
Will try investigate. Thanks for reporting.

One question: are the curtain sprites in that screenshot above aligned with the edge of the 19.5:9 display ?

**Comment by rabidgremlin** [comment]
Have not been able to replicate. Set up display (B) + letter boxer (C) for iPhone X resolution AND adjusted sprite positions to fit iPhone X resolution (A)

On playback game fits the full screen as expected (B):

![image](https://user-images.githubusercontent.com/444906/92438031-2e5b2800-f1fc-11ea-9af1-97ba75ab0591.png)

Then switched display to Sony Xperia 1 resolution and get black matt bars as expected which preserve the iPhoneX layout (C):

![SonyExperia](https://user-images.githubusercontent.com/444906/92438202-7da15880-f1fc-11ea-9ebd-17ed0b6b74bd.png)

**Comment by SyaoranChang** [comment]
This is my test project use Unity 2019.4.9f1.
Could you help me check my project settings?
[LetterBoxer.zip](https://github.com/rabidgremlin/LetterBoxer/files/5192311/LetterBoxer.zip)

**Comment by rabidgremlin** [comment]
Can you see if this work-around helps with your issue: https://github.com/rabidgremlin/LetterBoxer/issues/2
Thanks

**Comment by rabidgremlin** [comment]
Did the work around above help ? Also check out: https://github.com/rabidgremlin/LetterBoxer/issues/4#issuecomment-792062402 for instructions on how to ensure your camera and layout is correct (but use a 19.5:9 resolution instead)

**Comment by SyaoranChang** [comment]
Hi,

Today I clone project aging, and try the issue.
Maybe I misunderstanding by the curtain.
Seems work fine.

![Snipaste_2021-03-26_15-47-01](https://user-images.githubusercontent.com/18550228/112599243-a6acd200-8e4a-11eb-9313-d97dbb971990.png)

**Comment by rabidgremlin** [comment]
Excellent. In your case you would move the curtains to be at the edges for a 19.5.9 aspect ratio and then they would remain on the edges of the blue area regardless of the actual  display aspect ratio.
