### ISSUE TITLE
Mattes don't render on mobile

### ISSUE THREAD

**Issue by rabidgremlin** [rabidgremlin/LetterBoxer#2]
Mattes don't render on mobile devices. Instead part of screen is incorrectly rendered.

![Screenshot_20200909-155130](https://user-images.githubusercontent.com/444906/92552981-fb756a80-f2b5-11ea-8908-d75176c08fc1.png)

**Comment by rabidgremlin** [comment]
Work around is to add a second camera with a lower depth.

Use the following settings AND remove the "Audio Listener" on this second camera: 

![image](https://user-images.githubusercontent.com/444906/92553176-6de64a80-f2b6-11ea-85a6-e12304f7b197.png)

**Comment by SyaoranChang** [comment]
I add Matt Bar Camera and seems still has issue.
![Snipaste_2020-09-09_12-57-57](https://user-images.githubusercontent.com/18550228/92556556-d45e6f00-f29c-11ea-81e8-47f994a14e88.png)

**Comment by rabidgremlin** [comment]
Fixed in v1.1.0.
