### ISSUE TITLE
Joystick issue

### ISSUE THREAD

**Issue by chaoslejyonu** [rabidgremlin/LetterBoxer#3]
When I drag joystick to black bars it leave trails like this. How can I solve this thanks!
![issue](https://user-images.githubusercontent.com/69365871/93180700-39541200-f740-11ea-9e57-fb2d33162748.PNG)

**Comment by rabidgremlin** [comment]
Have you tried the "fix" detailed in https://github.com/rabidgremlin/LetterBoxer/issues/2

**Comment by rabidgremlin** [comment]
Any luck ?

**Comment by rabidgremlin** [comment]
Closing issue as no feedback. This issue should be fixed in latest release of component.
